# Rust edition
edition = "2024"

# Code Layout and Width
max_width = 100
use_small_heuristics = "Default"
tab_spaces = 4

# Type and Function Signature Formatting
use_field_init_shorthand = true

# Miscellaneous
merge_derives = true
